### ISSUE TITLE
Incorrect testing framework detected and selected (xUnit)

### ISSUE THREAD

**Issue by johnmbaughman** [Microsoft/UnitTestBoilerplateGenerator#40] opened 2018-11-15 23:21 UTC
### Installed product versions
- Visual Studio: 2017 Enterprise 15.9.0
- This extension: 1.9.10

### Description
Extension detects Visual Studio as test framework when xUnit is referenced.

### Steps to recreate
1. Create an xUnit test project
2. Reference xUnit in the project 
3. Click the extension menu
4. Dialog shows "Detected: Visual Studio" and selects the Visual Studio test framework
![image](https://user-images.githubusercontent.com/1634414/48587927-40b2f600-e8f2-11e8-8882-0520568000f3.png)

### Current behavior
Detects and selects incorrect test framework

### Expected behavior
Detect and select the correct test framework

**Comment by RandomEngy** [comment] 2018-11-16 07:34
I can't reproduce the issue. Can you try with Visual Studio 15.9.1? The extension was severely broken for me on 15.9.0. If it's still happening, can you share the .csproj file that the detection is failing on?

**Comment by johnmbaughman** [comment] 2018-11-16 16:43
Here are the project and package.config files. 

[UnitTestBoilerplateGenerator_Issue_40.zip](https://github.com/Microsoft/UnitTestBoilerplateGenerator/files/2590128/UnitTestBoilerplateGenerator_Issue_40.zip)

**Comment by RandomEngy** [comment] 2018-11-18 16:26
Looks like it was working in .NET Core projects but not .NET Framework projects. Updated to look for "xunit.core" as well as "xunit" references. Fix is in 1.9.12 .

Rate it on the Visual Studio Marketplace if you like the extension: https://marketplace.visualstudio.com/items?itemName=RandomEngy.UnitTestBoilerplateGenerator

**Comment by johnmbaughman** [comment] 2018-11-20 22:09
That worked. Now to fix the Assert.Fail() that doesn't exist in xUnit... ;)

I will go and rate this. It's awesome and saves a bunch of time.

**Closed as completed** 2018-11-21 18:28 UTC

**Comment by RandomEngy** [comment] 2018-12-07 07:38
In 1.9.13 I changed to use Assert.True(False) for xUnit.
