### ISSUE TITLE
Exception when clicking on "Create Unit test boilerpalte..."

### ISSUE THREAD

**Issue by binpick** [Microsoft/UnitTestBoilerplateGenerator#24] opened 2018-02-09 09:57 UTC
### Installed product versions
- Visual Studio: 2015 Community
- This extension: 1.7.0

### Description
This extension was working for a time. Now, every time i try to create a new xx i get the exception:

"The type initializer for UnitTestBoilerplate.StaticBoilerplateSettings threw an exception."

### Steps to recreate
1. Right click on any class
2. Select "Create Unit test boilerpalte..."

### Current behavior
No unit test file is created due to the exception.

### Expected behavior
A new unit test file should be created.

**Comment by binpick** [comment] 2018-02-09 10:06
I noticed that i am not able to save the boilerplate template settings. After e.g. resetting to default, i see the default template. After selecting ok and opening the settings again, all fields are empty.

**Comment by RandomEngy** [comment] 2018-02-09 15:13
Do you get any more details for the exception, like the stack trace? Or does it only say that it threw an exception and not tell you anything else?

**Comment by binpick** [comment] 2018-02-09 17:54
No, there is no stacktrace, just this exception message. Don't know if there is a log file somewhere?

**Comment by RandomEngy** [comment] 2018-02-10 21:48
Can you uninstall the extension and try this one? I added more logging that should tell me what's going on: http://engy.us/misc/UnitTestBoilerplate.vsix

**Comment by binpick** [comment] 2018-02-11 11:48
Thank you. I installed it and get the same exception. Where do i find the log file?

**Comment by binpick** [comment] 2018-02-11 11:48
Btw, i have this issue on different computers.

**Comment by binpick** [comment] 2018-02-11 11:49
...forgot to mention, great extension. I am using it in all of my projects, hope we can fix it :-)

**Comment by binpick** [comment] 2018-02-11 11:51
UTBG Self Test ->  Run:
"Sequence contains no matching element"

**Comment by binpick** [comment] 2018-02-11 11:54
If i reset UTGB settings to default, Visual Studio hangs and then it crashes (after pressing OK).

**Comment by binpick** [comment] 2018-02-11 11:56
This is from the windows event view:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at UnitTestBoilerplate.StaticBoilerplateSettings..cctor()

Exception Info: System.TypeInitializationException
   at UnitTestBoilerplate.ViewModel.FileContentsOptionsDialogViewModel.Apply()
   at UnitTestBoilerplate.View.FileContentsOptionsDialogPage.OnApply(PageApplyEventArgs)
   at Microsoft.VisualStudio.Shell.DialogPage+DialogSubclass.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr)

**Comment by binpick** [comment] 2018-02-11 11:58
So seems that i cannot save/load the settings. That's why the fields are empty when opening the settings. After resetting to default, VS crashes. Where are the settings stored?

In VS 2017 Community the extension works.

**Comment by RandomEngy** [comment] 2018-02-11 15:27
If you open VS, then right click on a file and select "Create Unit Test Boilerplate..." it should open a dialog box with more details this time. But that stack trace in the event log should give me somewhere to start, thanks.

**Comment by binpick** [comment] 2018-02-11 18:08
After right click i just get the expcetion window:

![image](https://user-images.githubusercontent.com/20605669/36076581-61ecbbf8-0f5e-11e8-820c-c2c61aff26ab.png)

I compared the settings of VS2017 and VS2015 in the registry and i noticed that the key where the settings are stored is missing for VS 2015. This explains why i am getting empty fields when opening the settings in VS 2015, but i don't know the reason.

VS 2017 (missing in VS 2015):
![image](https://user-images.githubusercontent.com/20605669/36076604-c9db60ac-0f5e-11e8-820a-062e96de5d19.png)

So seems that i cannot write the settings into the registry. Probably it is not a UTGB bug but a VS bug, but i dont' know the reason. I have it on different PCs.

**Comment by RandomEngy** [comment] 2018-02-11 21:13
Hmm, I installed VS 2015 community and everything is working fine over here. I'm rather surprised you're seeing the issue on multiple computers. What OS are you running?

One thing to remember about the registry is the \VisualStudio\14.0 is for VS 2015.
In VS 2017 (which is version 15, I know, confusing), whisks the registry settings off to some private place:

\REGISTRY\A\{f3b03746-a87a-c8bf-6859-2869b2937396}\Software\Microsoft\VisualStudio\15.0_a703f143\UnitTestBoilerplateGenerator\Template_VisualStudio_Moq_File

I'm also a bit surprised that with that .vsix you're still getting the old error dialog, as I put a giant try/catch around the StaticBoilerplateSettings static ctor. Are you sure you uninstalled the previous version?

**Comment by binpick** [comment] 2018-02-11 21:40
Hi, i am running Win10. I am going to deinstall the current version again, clean up the extension folder and reinstall it.

**Comment by binpick** [comment] 2018-02-11 21:57
I reinstalled and get the same error. Only the message box with the exception message. I do have the new version installed since i have the Self test menu, which i had not before. When trying to reset the settings VS crashes.

**Comment by RandomEngy** [comment] 2018-02-11 23:40
Curses! It sounds like something is causing SettingsManager.GetWritableSettingsStore to throw a FileNotFoundException, but I can't reproduce it. I'm running Win10 as well.

I'll try it on a clean Win10 VM.

**Comment by RandomEngy** [comment] 2018-02-12 05:58
Okay reproduced the error. Apparently Visual Studio stopped including Newtonsoft.Json in the VSIX output for some reason. Now I need to figure out why and how to include it again.

**Comment by RandomEngy** [comment] 2018-02-13 03:24
Should be fixed in 1.7.1.

**Closed as completed by RandomEngy** 2018-02-13 03:24 UTC

**Comment by binpick** [comment] 2018-02-13 21:49
Awesome. Thank you for the support, works like a charme.

**Comment by RandomEngy** [comment] 2018-02-16 17:21
Leave a review on the gallery page if you like the extension!

**Comment by binpick** [comment] 2018-02-22 19:52
You'r right, i did it.
